[package]
name = "curves"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
bignum = {tag = "v0.9.2-1", git = "https://github.com/zkpassport/noir-bignum"}
bigcurve = {tag = "v0.13.2-1", git = "https://github.com/zkpassport/noir_bigcurve"}
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }